<?php

namespace Yon\Bundle\ParisBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ApiContestType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
//            ->add('creation', 'datetime')
            ->add('name', null, array(
                    'label' => 'Titre',
                ))
//            ->add('trophyPictureUrl')
//            ->add('participantsCount')
//            ->add('autoGenerated')
            ->add('startDate', 'datetime', 
                array(
                    'widget' => 'single_text',
                    'label' => 'Horaire de début',
                    'format' => 'dd/MM/yyyy HH:mm'
                )
            )
            ->add('endDate', 'datetime', 
                array(
                    'widget' => 'single_text',
                    'label' => 'Horaire de fin',
                    'format' => 'dd/MM/yyyy HH:mm'
                )
            )
            ->add('description', null, array(
                    'label' => 'Description',
                ))
            ->add('plannedChallengesCount', null, array(
                    'label' => 'Nombre de paris',
                ))
//            ->add('hashtag')
//            ->add('user')
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Yon\Bundle\ParisBundle\Entity\ApiContest'
        ));
    }
}
