yon_rank:
    resource: "@YonRankBundle/Resources/config/routing.yml"
    prefix:   /

yon_badge:
    resource: "@YonBadgeBundle/Resources/config/routing.yml"
    prefix:   /

yon_paris:
    resource: "@YonParisBundle/Resources/config/routing.yml"
    prefix:   /

yon_privilege:
    resource: "@YonPrivilegeBundle/Resources/config/routing.yml"
    prefix:   /

yon_user:
    resource: "@YonUserBundle/Resources/config/routing.yml"
    prefix:   /
