services:
#    aci_user.example:
#        class: Aci\Bundle\UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    yon_user.data:
        class: Yon\Bundle\UserBundle\Service\Data
