parameters:
    yon_user.user_manager.class: Yon\Bundle\UserBundle\Manager\UserManager
    
services:
#    aci_user.example:
#        class: Aci\Bundle\UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    yon_user.data:
        class: Yon\Bundle\UserBundle\Service\Data
    yon_user.user_manager:
        class: %yon_user.user_manager.class%
        arguments: [@doctrine.orm.entity_manager]
