<?php

namespace Yon\Bundle\ParisBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * ApiContest
 *
 * @ORM\Table(name="api_contest", indexes={@ORM\Index(name="api_contest_e8701ad4", columns={"user_id"}), @ORM\Index(name="api_contest_e4858d5c", columns={"hashtag_id"})})
 * @ORM\Entity
 */
class ApiContest
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="creation", type="datetime", nullable=false)
     */
    private $creation;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=256, nullable=false)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="trophy_picture_url", type="string", length=100, nullable=true)
     */
    private $trophyPictureUrl;

    /**
     * @var integer
     *
     * @ORM\Column(name="participants_count", type="integer", nullable=false)
     */
    private $participantsCount;

    /**
     * @var boolean
     *
     * @ORM\Column(name="auto_generated", type="boolean", nullable=false)
     */
    private $autoGenerated;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="end_date", type="datetime", nullable=false)
     */
    private $endDate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="start_date", type="datetime", nullable=false)
     */
    private $startDate;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=256, nullable=true)
     */
    private $description;

    /**
     * @var integer
     *
     * @ORM\Column(name="planned_challenges_count", type="integer", nullable=true)
     */
    private $plannedChallengesCount;

    /**
     * @var \ApiHashtag
     *
     * @ORM\ManyToOne(targetEntity="ApiHashtag")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="hashtag_id", referencedColumnName="id")
     * })
     */
    private $hashtag;

    /**
     * @var \AuthUser
     *
     * @ORM\ManyToOne(targetEntity="\Yon\Bundle\UserBundle\Entity\AuthUser")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     * })
     */
    private $user;
    
    /**
     * @var \ApiContestChallenge
     *
     * @ORM\OneToMany(targetEntity="ApiContestchallenge", mappedBy="contest")
     */
    private $contestChallenge;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->contestChallenge = new \Doctrine\Common\Collections\ArrayCollection();
        $this->setCreation ( new \DateTime () );
        $this->setParticipantsCount (0);
        $this->setAutoGenerated (0);
    }
    
    /**
     * Add contestChallenge
     *
     * @param \Yon\Bundle\ParisBundle\Entity\ApiContestChallenge $contestChallenge
     * @return ApiChallenge
     */
    public function addContestChallenge(\Yon\Bundle\ParisBundle\Entity\ApiContestChallenge $contestChallenge)
    {
        $this->contestChallenge[] = $contestChallenge;

        return $this;
    }

    /**
     * Remove contestChallenge
     *
     * @param \Yon\Bundle\ParisBundle\Entity\ApiContestChallenge $contestChallenge
     */
    public function removeContestChallenge(\Yon\Bundle\ParisBundle\Entity\ApiContestChallenge $contestChallenge)
    {
        $this->contestChallenge->removeElement($contestChallenge);
    }

    /**
     * Get contestChallenge
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getContestChallenge()
    {
        return $this->contestChallenge;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set creation
     *
     * @param \DateTime $creation
     * @return ApiContest
     */
    public function setCreation($creation)
    {
        $this->creation = $creation;

        return $this;
    }

    /**
     * Get creation
     *
     * @return \DateTime 
     */
    public function getCreation()
    {
        return $this->creation;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return ApiContest
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set trophyPictureUrl
     *
     * @param string $trophyPictureUrl
     * @return ApiContest
     */
    public function setTrophyPictureUrl($trophyPictureUrl)
    {
        $this->trophyPictureUrl = $trophyPictureUrl;

        return $this;
    }

    /**
     * Get trophyPictureUrl
     *
     * @return string 
     */
    public function getTrophyPictureUrl()
    {
        return $this->trophyPictureUrl;
    }

    /**
     * Set participantsCount
     *
     * @param integer $participantsCount
     * @return ApiContest
     */
    public function setParticipantsCount($participantsCount)
    {
        $this->participantsCount = $participantsCount;

        return $this;
    }

    /**
     * Get participantsCount
     *
     * @return integer 
     */
    public function getParticipantsCount()
    {
        return $this->participantsCount;
    }

    /**
     * Set autoGenerated
     *
     * @param boolean $autoGenerated
     * @return ApiContest
     */
    public function setAutoGenerated($autoGenerated)
    {
        $this->autoGenerated = $autoGenerated;

        return $this;
    }

    /**
     * Get autoGenerated
     *
     * @return boolean 
     */
    public function getAutoGenerated()
    {
        return $this->autoGenerated;
    }

    /**
     * Set endDate
     *
     * @param \DateTime $endDate
     * @return ApiContest
     */
    public function setEndDate($endDate)
    {
        $this->endDate = $endDate;

        return $this;
    }

    /**
     * Get endDate
     *
     * @return \DateTime 
     */
    public function getEndDate()
    {
        return $this->endDate;
    }

    /**
     * Set startDate
     *
     * @param \DateTime $startDate
     * @return ApiContest
     */
    public function setStartDate($startDate)
    {
        $this->startDate = $startDate;

        return $this;
    }

    /**
     * Get startDate
     *
     * @return \DateTime 
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return ApiContest
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set plannedChallengesCount
     *
     * @param integer $plannedChallengesCount
     * @return ApiContest
     */
    public function setPlannedChallengesCount($plannedChallengesCount)
    {
        $this->plannedChallengesCount = $plannedChallengesCount;

        return $this;
    }

    /**
     * Get plannedChallengesCount
     *
     * @return integer 
     */
    public function getPlannedChallengesCount()
    {
        return $this->plannedChallengesCount;
    }

    /**
     * Set hashtag
     *
     * @param \Yon\Bundle\ParisBundle\Entity\ApiHashtag $hashtag
     * @return ApiContest
     */
    public function setHashtag(\Yon\Bundle\ParisBundle\Entity\ApiHashtag $hashtag = null)
    {
        $this->hashtag = $hashtag;

        return $this;
    }

    /**
     * Get hashtag
     *
     * @return \Yon\Bundle\ParisBundle\Entity\ApiHashtag 
     */
    public function getHashtag()
    {
        return $this->hashtag;
    }

    /**
     * Set user
     *
     * @param \Yon\Bundle\UserBundle\Entity\AuthUser $user
     * @return ApiContest
     */
    public function setUser(\Yon\Bundle\UserBundle\Entity\AuthUser $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \Yon\Bundle\UserBundle\Entity\AuthUser 
     */
    public function getUser()
    {
        return $this->user;
    }
    
    public function getParisJoue() {
        $cnt = 0;
        if( count($this->getContestChallenge()) > 0 ){
            foreach ($this->getContestChallenge() as $contestChallenge) {
                $challenge = $contestChallenge->getChallenge();
                if($challenge->getBetsCount() > 0){
                    $cnt = $cnt + 1;
                }
            }
        }
        
        return $cnt;
    }
}
