apifeature_index:
    path:     /
    defaults: { _controller: "YonPrivilegeBundle:ApiFeature:index" }
    methods:  GET

apifeature_show:
    path:     /{id}/show
    defaults: { _controller: "YonPrivilegeBundle:ApiFeature:show" }
    methods:  GET

apifeature_new:
    path:     /new
    defaults: { _controller: "YonPrivilegeBundle:ApiFeature:new" }
    methods:  [GET, POST]

apifeature_edit:
    path:     /{id}/edit
    defaults: { _controller: "YonPrivilegeBundle:ApiFeature:edit" }
    methods:  [GET, POST]

apifeature_delete:
    path:     /{id}/delete
    defaults: { _controller: "YonPrivilegeBundle:ApiFeature:delete" }
    methods:  DELETE
