yon_paris_apichallenge:
    resource: "@YonParisBundle/Resources/config/routing/apichallenge.yml"
    prefix:   /paris
    
yon_paris_list_ajax:
    path:   /paris/list-ajax
    defaults: { _controller: "YonParisBundle:ApiChallenge:parisListAjax" }
    options:
        expose: true